service: project-rutherford
frameworkVersion: '3'

plugins:
  - serverless-python-requirements
  - serverless-offline
provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  get-quotes:
    handler: handlers/get_quotes.handler
    role: getQuotesFunctionExecutionRole
    events:
      - httpApi:
          path: /api/v1/quotes
          method: get

resources:
  Resources:
    getQuotesFunctionExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: project-rutherford-get-quotes-lambda-execution-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: project-rutherford-lambda-cloudwatch-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/project-rutherford:*:*'
          - PolicyName: project-rutherford-lambda-s3-read
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Resource: arn:aws:s3:::project-rutherford-65819/*
                  Action: s3:GetObject
