AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for S3 bucket
Resources:
  QuotesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: project-rutherford-65819
Outputs:
  QuotesBucket:
    Description: Quotes bucket
    Value: !GetAtt [ QuotesBucket, Arn ]
    Export:
      Name: !Sub "${AWS::StackName}--S3Bucket-ARN"