AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for new subscriberSNS messaging
Resources:
  NewSubscriberTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: project-rutherford-new-subscriber-topic
      Subscription:
        - Protocol: email
          Endpoint: rutherford.master@yopmail.com

Outputs:
  TopicArn:
    Description: New Subscriber Topic Name
    Value: !Ref NewSubscriberTopic
    Export:
      Name: !Sub "${AWS::StackName}--NewSubscriber-ARN"